Add APP_SCRIPT variable

diff --git a/3.5/s2i/bin/run b/3.5/s2i/bin/run
--- a/3.5/s2i/bin/run
+++ b/3.5/s2i/bin/run
@@ -32,6 +32,15 @@ function get_default_web_concurrency() {
   echo $default
 }
 
+app_script_check="${APP_SCRIPT-}"
+APP_SCRIPT="${APP_SCRIPT:-app.sh}"
+if [[ -x "$APP_SCRIPT" ]]; then
+  echo "---> Running application from script ($APP_SCRIPT) ..."
+  exec $(readlink -e $APP_SCRIPT)
+else
+  test -n "$app_script_check" && (>&2 echo "ERROR: file '$app_script_check' not found.") && exit 1
+fi
+
 app_file_check="${APP_FILE-}"
 APP_FILE="${APP_FILE:-app.py}"
 if [[ -f "$APP_FILE" ]]; then
@@ -87,5 +96,5 @@ if is_django_installed; then
 fi
 
 >&2 echo "ERROR: don't know how to run your application."
->&2 echo "Please set either APP_MODULE or APP_FILE environment variables, or create a file 'app.py' to launch your application."
+>&2 echo "Please set either APP_MODULE, APP_FILE or APP_SCRIPT environment variables, or create an 'app.py' or 'app.sh' file to launch your application."
 exit 1
